console.log('hello, world');
var heading = document.querySelector('h1');
console.log('h1:', heading);
console.dir(heading);
var explanation = document.querySelector('#explanation');
console.log('explanation', explanation);
console.dir(explanation);
var hint = document.querySelector('.hint');
console.log('hint', hint);
console.dir(hint);
var paragraph = document.querySelectorAll('p');
console.log('paragraph', paragraph);
var exampleLink = document.querySelectorAll('.example-link');
console.log('exampleLink', exampleLink);
